### PR TITLE
create translation.tw.json

### PR DESCRIPTION
**Pull request by blacky0301**
Traditional Chinese Translation.

dunno if i'm doing right or not,
I am totally not a programmer.
but still hope it helps, thanks.

### CODE REVIEW

**Comment by msx752** [comment]
@blacky0301  thanks. i will check :+1:

**Comment by msx752** [comment]
@blacky0301  i added but some encoding problems appeared, now not working,
 im worknig on

**Comment by msx752** [comment]
@blacky0301  can you try the translation.  i cant check Chinese letters

**Comment by blacky0301** [comment]
@msx752 i let it autoupdate 3mins ago, 

did not try all the messages, but mostly works fine.

**Comment by msx752** [comment]
my computer doesn't support Chinese letters, if you say okey its good :+1:

**Comment by blacky0301** [comment]
yes it works .

thank you.

**Pull request merged**
